[2025-07-11T15:11:07.963+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-10T00:00:00+00:00/task_id=tune_model permission to 509
[2025-07-11T15:11:07.964+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-10T00:00:00+00:00/task_id=tune_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-10T00:00:00+00:00/task_id=tune_model'
[2025-07-11T15:11:08.042+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-10T00:00:00+00:00/task_id=tune_model permission to 509
[2025-07-11T15:11:08.044+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-10T00:00:00+00:00/task_id=tune_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-10T00:00:00+00:00/task_id=tune_model'
[2025-07-11T15:11:08.129+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-10T00:00:00+00:00 [queued]>
[2025-07-11T15:11:08.146+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-10T00:00:00+00:00 [queued]>
[2025-07-11T15:11:08.147+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-11T15:11:08.177+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): tune_model> on 2025-07-10 00:00:00+00:00
[2025-07-11T15:11:08.184+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2025-07-11T15:11:08.191+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'tune_model', 'scheduled__2025-07-10T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmpjftw2ndf']
[2025-07-11T15:11:08.195+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask tune_model
[2025-07-11T15:11:08.232+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-11T15:11:08.329+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-10T00:00:00+00:00/task_id=tune_model permission to 509
[2025-07-11T15:11:08.330+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-10T00:00:00+00:00/task_id=tune_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-10T00:00:00+00:00/task_id=tune_model'
[2025-07-11T15:11:08.334+0000] {task_command.py:416} INFO - Running <TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-10T00:00:00+00:00 [running]> on host 961842f4d5ed
[2025-07-11T15:11:08.526+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='tune_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-10T00:00:00+00:00'
[2025-07-11T15:11:08.529+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-11T15:11:08.531+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            python /opt/***/pipeline/tune_model.py\n        ']
[2025-07-11T15:11:08.550+0000] {subprocess.py:86} INFO - Output:
[2025-07-11T15:11:10.444+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-11T15:11:10.446+0000] {subprocess.py:93} INFO -   File "/opt/***/pipeline/tune_model.py", line 4, in <module>
[2025-07-11T15:11:10.449+0000] {subprocess.py:93} INFO -     import mlflow
[2025-07-11T15:11:10.450+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'mlflow'
[2025-07-11T15:11:10.601+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-11T15:11:10.623+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-11T15:11:10.630+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=tune_model, execution_date=20250710T000000, start_date=20250711T151108, end_date=20250711T151110
[2025-07-11T15:11:10.654+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task tune_model (Bash command failed. The command returned a non-zero exit code 1.; 62)
[2025-07-11T15:11:10.673+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-11T15:11:10.723+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
