[2025-07-12T09:15:51.569+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-11T00:00:00+00:00/task_id=tune_model permission to 509
[2025-07-12T09:15:51.570+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-11T00:00:00+00:00/task_id=tune_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-11T00:00:00+00:00/task_id=tune_model'
[2025-07-12T09:15:51.632+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-11T00:00:00+00:00/task_id=tune_model permission to 509
[2025-07-12T09:15:51.633+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-11T00:00:00+00:00/task_id=tune_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-11T00:00:00+00:00/task_id=tune_model'
[2025-07-12T09:15:51.692+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-11T00:00:00+00:00 [queued]>
[2025-07-12T09:15:51.706+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-11T00:00:00+00:00 [queued]>
[2025-07-12T09:15:51.707+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-12T09:15:51.737+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): tune_model> on 2025-07-11 00:00:00+00:00
[2025-07-12T09:15:51.747+0000] {standard_task_runner.py:57} INFO - Started process 514 to run task
[2025-07-12T09:15:51.767+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'turnstile_ml_pipeline', 'tune_model', 'scheduled__2025-07-11T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_dag.py', '--cfg-path', '/tmp/tmp9bp6jkny']
[2025-07-12T09:15:51.772+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask tune_model
[2025-07-12T09:15:51.796+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-12T09:15:51.858+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-11T00:00:00+00:00/task_id=tune_model permission to 509
[2025-07-12T09:15:51.859+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-11T00:00:00+00:00/task_id=tune_model permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=turnstile_ml_pipeline/run_id=scheduled__2025-07-11T00:00:00+00:00/task_id=tune_model'
[2025-07-12T09:15:51.862+0000] {task_command.py:416} INFO - Running <TaskInstance: turnstile_ml_pipeline.tune_model scheduled__2025-07-11T00:00:00+00:00 [running]> on host 961842f4d5ed
[2025-07-12T09:15:51.993+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='turnstile_ml_pipeline' AIRFLOW_CTX_TASK_ID='tune_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-11T00:00:00+00:00'
[2025-07-12T09:15:51.995+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-12T09:15:51.997+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            python /opt/***/pipeline/tune_model.py\n        ']
[2025-07-12T09:15:52.012+0000] {subprocess.py:86} INFO - Output:
[2025-07-12T09:15:53.305+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-12T09:15:53.305+0000] {subprocess.py:93} INFO -   File "/opt/***/pipeline/tune_model.py", line 4, in <module>
[2025-07-12T09:15:53.306+0000] {subprocess.py:93} INFO -     import mlflow
[2025-07-12T09:15:53.307+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'mlflow'
[2025-07-12T09:15:53.404+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-12T09:15:53.417+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-12T09:15:53.424+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=turnstile_ml_pipeline, task_id=tune_model, execution_date=20250711T000000, start_date=20250712T091551, end_date=20250712T091553
[2025-07-12T09:15:53.444+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task tune_model (Bash command failed. The command returned a non-zero exit code 1.; 514)
[2025-07-12T09:15:53.461+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-12T09:15:53.505+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
